DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS EMPLOYEE_INCENTIVE;

CREATE TABLE EMPLOYEE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  salary INT,
  age INT,
  dob DATE,
  contact INT NOT NULL,
  rating INT
);

CREATE TABLE EMPLOYEE_INCENTIVE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  employee_id VARCHAR(250) NOT NULL,
  amount INT DEFAULT 0,
  incentive_date DATE DEFAULT NULL
);